### ISSUE TITLE
Description and placeholders

### ISSUE THREAD

**Issue by lucarabistouille** [rezometz/django-paiji2-forum#11]
When writing a new message, a text is pre-inputed in the textarea : 
`<textarea>Utilisez ici le format *Markdown*.  Cf. [documentation](http://daringfireball.net/projects/markdown/basics).</textarea>`

I think it could be more practical to have something like : 
`<textarea placeholder="Utilisez ici le format *Markdown*.  Cf. [documentation](http://daringfireball.net/projects/markdown/basics").></textarea>`

`placeholders` attribute is specially designed for that.

**Comment by LGD-Fr** [comment]
The placeholder property is not taken into account by the JS function displaying the HTML output… sorry :-(
