### ISSUE TITLE
Ordre des discussions

### ISSUE THREAD

**Issue by lucarabistouille** [rezometz/django-paiji2-forum#3]
Bonjour,

Ne serait-il pas souhaitable d'ordonner les discussions dans l'ordre chronologique, mais non pas suivant le premier message, mais au contraire suivant le dernier message de la discussion ?

**Comment by LGD-Fr** [comment]
Non, je ne pense pas.

**Comment by luc--** [comment]
Je pensais cela car cela permettrait de faire remonter des discussions ; actuellement si l'on poste un message sur une ancienne discussion, il est difficilement visible des autres utilisateurs.

**Comment by LGD-Fr** [comment]
Pas le moins du monde: le message est en bonne position dans:
- messages récents ;
- messages non lus.
Et il y a même un étiquette bleue.

**Comment by luc--** [comment]
En effet : peut-être pourrait-on envisager de garder une certaine arborescence dans les messages récents alors ?

**Comment by LGD-Fr** [comment]
laquelle @luc-- ?

**Comment by luc--** [comment]
Celle qui conduit jusqu'au message actuel, ou bien la totalité ?

**Comment by LGD-Fr** [comment]
Ce serait plus coûteux en calcul.

**Comment by luc--** [comment]
Pas plus que la page discussions, il me semble...

**Comment by luc--** [comment]
Euh pourquoi avoir supprimé tous les messages ?

**Comment by lucarabistouille** [comment]
Quant au sujet en lui-même, il me semble possible de créer la fonctionnalité plutôt que de faire évoluer celles déjà existantes, puisque tu y semblais réticent dans les messages que tu as supprimé.

**Comment by LGD-Fr** [comment]
J’y réfléchis @luc--

**Comment by LGD-Fr** [comment]
content @luc-- ;-)

**Comment by lucarabistouille** [comment]
Ah j'étais prêt à le faire tu sais :)

Merci :)

Sur 9 oct. 2015 18:24, à 18:24, Louis-Guillaume Dubois notifications@github.com a écrit:
