### ISSUE TITLE
use bleach instead of the "removetags" filter

### ISSUE THREAD

**Issue by LGD-Fr** [rezometz/django-paiji2-forum#4]
to remove _script_ or _iframe_ nodes in markdown messages.

_removetags_ is deprecated.

**Comment by ghost** [comment]
Yet it will never bring me back my love.

2015-10-23 22:27 GMT+02:00 Louis-Guillaume Dubois notifications@github.com
:

**Comment by LGD-Fr** [comment]
@Paul-FM-Muller les exactions de quelques uns malheureusement font retomber le châtiment sur tous…

**Comment by LGD-Fr** [comment]
<script>alert('test')</script>

**Comment by lucarabistouille** [comment]
Les boucles infinies de LGD ?

**Comment by LGD-Fr** [comment]
@luc-- les boucles finies c’est pour les faibles ;-)

**Comment by LGD-Fr** [comment]
No more django-markdown with Django==1.10 this time.
